# Site title and description
title: "Elca"
title_short: ""
description: "Your site description"
keywords: "your,keywords,here"
author: "Qxel"
remote_theme: LittleCeo/elca

plugins:
  - jekyll-remote-theme
# Logo (optional)
logo: "https://Littleceo.github.io/logos/elca.png" # Path to your logo

# NEW Navigation configuration - Updated for the new navigation system
# NEW Navigation configuration - Updated for the new navigation system
navigation:
  - title: "Home"
    url: "/"
  - title: "Adnan"
    type: "folder"
    url: "/adnan"
    children:
      - title: "Assignment"
        url: "/adnan/assignment"
      - title: "Seminar"
        url: "/adnan/seminar"
  - title: "Jaseel"
    type: "folder"
    url: "/jaseel"
    children:
      - title: "Assignment"
        url: "/jaseel/assignment"
      - title: "Athulya Assignment"
        url: "/jaseel/athulya_assignment"
      - title: "Navas Assignment"
        url: "/jaseel/navas_assignment"
  - title: "My Notes"
    type: "folder"
    url: "/my"
    children:
      - title: "Aseena Assignment"
        url: "/my/aseena_assignment"
      - title: "Aseena Seminar"
        url: "/my/aseena_seminar"
      - title: "Assignment"
        url: "/my/assignment"
      - title: "Athulya Assignment"
        url: "/my/athulya_assignment"
      - title: "Seminar"
        url: "/my/seminar"
      - title: "Suji Assignment"
        url: "/my/suji_assignment"
      - title: "Suji Seminar"
        url: "/my/suji_seminar"
  - title: "Noushique"
    type: "folder"
    url: "/noushique"
    children:
      - title: "Assignment"
        url: "/noushique/assignment"
      - title: "Seminar"
        url: "/noushique/seminar"
  - title: "BCA"
    type: "folder"
    url: "/sinan"
    children:
      - title: "Sinan Assignment"
        url: "/sinan/assignment"
  - title: "Calicut"
    type: "folder"
    url: "/calicut"
    children:
      - title: "BEPOLI"
        type: "folder"
        url: "/calicut/bepoli"
        children:
          - title: "Operating Project"
            url: "/calicut/bepoli/op"
      - title: "NIKKOLA"
        type: "folder"
        url: "/calicut/nikkola"
        children:
          - title: "Nokil project"
            url: "/calicut/nikkola/noki"
